# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

before_script:
  - echo "Iniciando Script CI"
  - export JAVA_HOME=/opt/jdk1.7.0_80
  - export PATH=$JAVA_HOME/bin:$PATH
   
variables:
  MAVEN_CLI_OPTS: "--batch-mode"

after_script:
  - echo "Finalizando Script CI"
   
stages:
  - build_java
  - test_java
  - deploy_maven

build_java:
  stage: build_java
  script:
    - cd $CI_PROJECT_DIR
    - ./mvnw $MAVEN_CLI_OPTS -Pshaded -DskipTests clean install
   
test_java:
  stage: test_java
  script: 
    - cd $CI_PROJECT_DIR
    - ./mvnw $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit:
        - $CI_PROJECT_DIR/target/surefire-reports/TEST-*.xml
#        - target/failsafe-reports/TEST-*.xml
  
deploy_maven:
  stage: deploy_maven
  script:
    - cd $CI_PROJECT_DIR
    - ./mvnw $MAVEN_CLI_OPTS deploy
